name: A workflow for my Hello World file
on: 
  workflow_dispatch:
    inputs:
      test_command: 
        description: 'enter the command to run'
        required: true
        type: string

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'printing the inptus'
        run: echo the test command is are ${{ github.events.inputs.test_command }}
      # - uses: ./action-a
        # with:
          # MY_NAME: "Frozen"
